service: sample-lambda-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  hello:
    handler: handler.router
    events:
      - httpApi:
          method: "*"
          path: "*"

plugins:
  - serverless-offline
